package com.galeria.defensores.data

import com.galeria.defensores.models.ChatMessage
import com.google.firebase.firestore.FirebaseFirestore
import com.google.firebase.firestore.Query
import kotlinx.coroutines.channels.awaitClose
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.callbackFlow
import kotlinx.coroutines.tasks.await
import javax.inject.Inject
import javax.inject.Singleton

@Singleton
class ChatRepository @Inject constructor() {

    private val db = FirebaseFirestore.getInstance()

    fun getMessagesFlow(tableId: String): Flow<List<ChatMessage>> = callbackFlow {
        val query = db.collection("tables")
            .document(tableId)
            .collection("messages")
            .orderBy("timestamp", Query.Direction.ASCENDING) // Order by oldest first for chat list (or DESC and reverse list)
            .limitToLast(50)

        val listener = query.addSnapshotListener { snapshot, error ->
            if (error != null) {
                close(error)
                return@addSnapshotListener
            }

            if (snapshot != null) {
                val messages = snapshot.documents.mapNotNull { doc ->
                    doc.toObject(ChatMessage::class.java)?.copy(id = doc.id)
                }
                trySend(messages)
            }
        }

        awaitClose { listener.remove() }
    }

    suspend fun sendMessage(tableId: String, message: ChatMessage) {
        // ID is auto-generated by Firestore
        db.collection("tables")
            .document(tableId)
            .collection("messages")
            .add(message)
            .await()
    }
}
